{{- define "params" -}}
  {{- $parameters := index . 1 -}}
- name: SDK_IMAGE
  description: Fully qualified name of the SDK image.
  type: string
{{ if has "PROJECT" $parameters -}}
- name: PROJECT
  description: Path of the .NET project file in the source workspace.
  type: string
{{ end -}}
{{ if has "IMAGE_NAME" $parameters -}}
- name: IMAGE_NAME
  description: |
    Name of the application image repository to push to.
    When the name does not include a registry, the 'SDK_IMAGE' registry is used.
  type: string
{{ end -}}
{{ if has "BASE_IMAGE" $parameters -}}
- name: BASE_IMAGE
  description: |
    When set, overrides the base image used for the application image.
    When the name does not include a registry, the 'SDK_IMAGE' registry is used.
    The current Kubernetes namespace can be used via '$(context.taskRun.namespace)'.
  type: string
  default: ""
{{ end -}}
{{ if has "SCRIPT" $parameters -}}
- name: SCRIPT
  description: The script to run.
  type: string
  default: dotnet --info
{{ end -}}
{{ if has "VERBOSITY" $parameters -}}
- name: VERBOSITY
  description: MSBuild verbosity level. Allowed values are 'q[uiet]', 'm[inimal]', 'n[ormal]', 'd[etailed]', and 'diag[nostic]'.
  default: "minimal"
  type: string
{{ end -}}
{{ if has "BUILD_PROPS" $parameters -}}
- name: BUILD_PROPS
  type: array
  description: MSBuild properties to pass to the publish command.
  default: []
{{ end -}}
- name: ENV_VARS
  type: array
  description: Environment variables.
  default: []
{{ end -}}